id: d2e8a8bb326f4f29b7578fe745d61f01
initial_creation_type: ocr
source_metadata:
  volumes:
    b71299cca0014dc2aa9661a279386df5:
      base_file: v059.txt
      image_group_id: I1PD95905
      title: ''
      total_pages: 1913
      volume_number: 60
